services:
  - type: web
    name: secure-cloud-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAIL_USERNAME
        value: your_email@example.com
      - key: MAIL_PASSWORD
        value: your_email_password_or_app_password
