services:
  - type: web
    name: secure-upload-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_USER
        value: yourname@gmail.com
      - key: EMAIL_PASS
        value: your-16-digit-app-password
